[package]
name = "sauna"
version = "0.1.0"
authors = ["pi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.22.4"
serde = "1.0.94"
serde_json = "1.0.40"
serde_derive = "1.0"